import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Andy's Overwatch Highlights",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="bg-[url('/ow-bg4.png')] bg-cover background-container -z-10"></div>
        {children}
      </body>
    </html>
  );
}
